package com.github.lucascalheiros.waterreminder.measuresystem.domain.repositories

import com.github.lucascalheiros.waterreminder.measuresystem.domain.models.MeasureSystemTemperatureUnit

interface TemperatureUnitRepository: BaseUnitRepository<MeasureSystemTemperatureUnit>